version: '3'
services:
  todo-inspectit:
    image: inspectit/inspectit-ocelot-agent:latest
    container_name: todo-inspectit
    volumes:
      - agent-vol:/agent

## Database

  todo-db:
    image: postgres
    container_name: todo-db
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: tododb
    ports:
      - 5432:5432

  todo-db-exporter:
    image: wrouesnel/postgres_exporter:latest
    container_name: todo-db-exporter
    depends_on:
      - todo-db
    volumes:
      - ./config/queries.yml:/etc/config/queries.yml
    environment:
      DATA_SOURCE_NAME: postgresql://todo:todo@todo-db:5432/tododb?sslmode=disable #<username>:<password>@<server>:<port>/<database>
      PG_EXPORTER_EXTEND_QUERY_PATH: /etc/config/queries.yml
      PG_EXPORTER_DISABLE_DEFAULT_METRICS: "false"
    ports:
      - 9187:9187

## App

  todo-app:
    image: todolist
    container_name: todo-app
    depends_on:
      - todo-db
      - todo-inspectit
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://todo-db:5432/tododb
      SPRING_DATASOURCE_USERNAME: todo
      SPRING_DATASOURCE_PASSWORD: todo
      INSPECTIT_SERVICE_NAME: todo-app
      INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT: 8888
      INSPECTIT_SELF_MONITORING_ENABLED: "true"
      INSPECTIT_CONFIG_FILE_BASED_PATH: /agentconfig
    entrypoint: ["sh", "-c", "java -javaagent:/agent/inspectit-ocelot-agent.jar -jar /app.jar"]
    volumes:
      - ./config/inspectit:/agentconfig
      - agent-vol:/agent
    ports:
      - 5555:5555
      - 8888:8888

## Monitoring

  todo-prometheus:
    image: prom/prometheus:latest
    container_name: todo-prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  todo-grafana:
    image: grafana/grafana:latest
    container_name: todo-grafana
    volumes:
      - ./grafana/provisioning:/usr/share/grafana/custom/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=todo
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
    ports:
      - 3000:3000

volumes:
  agent-vol: