apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-app
  name: todo-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: todo-app
    spec:
      containers:
      - command:
        - sh
        - -c
        - java -javaagent:/agent/inspectit-ocelot-agent.jar -jar /app.jar
        env:
        - name: INSPECTIT_CONFIG_FILE_BASED_PATH
          value: /agentconfig
        - name: INSPECTIT_EXPORTERS_METRICS_PROMETHEUS_PORT
          value: "8888"
        - name: INSPECTIT_SELF_MONITORING_ENABLED
          value: "true"
        - name: INSPECTIT_SERVICE_NAME
          value: todo-app
        - name: SPRING_DATASOURCE_PASSWORD
          value: todo
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://todo-db:5432/tododb
        - name: SPRING_DATASOURCE_USERNAME
          value: todo
        image: todolist
        name: todo-app
        ports:
        - containerPort: 5555
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /agentconfig
          name: todo-app-claim0
        - mountPath: /agent
          name: agent-vol
      restartPolicy: Always
      volumes:
      - name: todo-app-claim0
        persistentVolumeClaim:
          claimName: todo-app-claim0
      - name: agent-vol
        persistentVolumeClaim:
          claimName: agent-vol
status: {}
