apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-agent-pv
  namespace: todo-application
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/home/monitor/ownCloud/MonitoringCloud/monitoring-todolist/agent/"
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-agent-claim
  namespace: todo-application
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi