apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-agent-pv
  namespace: todo-application
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/monitor/ownCloud/MonitoringCloud/monitoring-todolist/agent/"
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-agent-claim
  namespace: todo-application
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: todo-inspectit
  name: todo-inspectit
  namespace: todo-application
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: todo-inspectit
    spec:
      containers:
        - image: inspectit/inspectit-ocelot-agent:latest
          name: todo-inspectit
          resources: {}
          volumeMounts:
            - name: todo-agent-volume
              mountPath: /agent
      restartPolicy: Always
      volumes:
        - name: todo-agent-volume
          hostPath:
          persistentVolumeClaim:
            claimName: todo-agent-claim
status: {}
